# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1S8-uqcxgGtl8wMwoDVLxDRyXF2mzFms5
"""



!pip install pytelegrambotapi



git remote add origin https://github.com/sanakcx/tg_bot.project.git
git branch -M main
git push -u origin main

import telebot
from telebot import types
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont

bot = telebot.TeleBot('5116477930:AAE8LAlx2UOdsTK2IhLEgmwj5CflWmZ-ki4')

@bot.message_handler(commands=['start'])
def start(message):
  chat_id = message.chat.id
  first_name = message.chat.first_name
  markup = types.ReplyKeyboardMarkup(resize_keyboard=True)
  keyboard = types.KeyboardButton(text='меню')
  markup.add(keyboard)
  bot.send_message(chat_id, f'Привет {first_name}', reply_markup=markup)




@bot.message_handler(content_types=['text'])
def text(message):
  chat_id = message.chat.id
  if message.chat.type == 'private':
    if message.text == 'меню':
      bot.send_message(chat_id, f'Отправь мне фотографию' )

def generate_doc(message):

  img = Image.open('1.jpg')

  font = ImageFont.truetype('font.ttf',30) # Загрузка шрифта и установка размера
  font_color = (74,75,69) # Цвет шрифта
  text = (585,172) # Координаты первой буквы фамилии на картинке 1.jpg

  drawing = ImageDraw.Draw(img)
  drawing.text(text,message,font=font,fill=font_color)

  return img


def repeat_all_message(message):

  string = message.text
  image.save('test.jpg')
  bot.send_photo(message.chat.id,photo=open('test.jpg','rb'))




bot.polling(none_stop=True)



